// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tlcbgnczxrrpqvmronid.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRsY2JnbmN6eHJycHF2bXJvbmlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM4NjQ5NTIsImV4cCI6MjA0OTQ0MDk1Mn0.LuS2RlHRcRRYUie81LxPkDB_I6YHxH_znd3_sTxuMEs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);